return {
	"nvim-treesitter/nvim-treesitter",
	event = { "BufReadPre", "BufNewFile" },
	build = ":TSUpdate",
	dependencies = {
		"windwp/nvim-ts-autotag",
	},
	config = function()
		local treesitter = require("nvim-treesitter.configs")

		treesitter.setup({
			highlight = {
				enable = true,
			},
			indent = { enable = true },
			autotag = {
				enable = true,
			},
			ensure_installed = {
				"arduino",
				"asm",
				"bash",
				"bibtex",
				"c",
				"c_sharp",
				"cmake",
				"comment",
				"cpp",
				"css",
				"csv",
				"dart",
				"disassembly",
				"dockerfile",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"haskell",
				"html",
				"java",
				"javascript",
				"json",
				"jq",
				"julia",
				"latex",
				"llvm",
				"lua",
				"luadoc",
				"luap",
				"markdown",
				"markdown_inline",
				"meson",
				"ninja",
				"psv",
				"python",
				"rasi",
				"regex",
				"rust",
				"scala",
				"sql",
				"tmux",
				"verilog",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
				"go",
			},
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<C-space>",
					node_incremental = "<C-space>",
					scope_incremental = false,
					node_decremental = "<bs>",
				},
			},
		})
	end,
}
